- type: latheRecipePack
  id: TraumaSecurityWeapons
  recipes:
  - PolymerBaton
  - SpearTelescopic
  - WeaponBillyClub

- type: latheRecipePack
  id: TraumaSecurityMechParts
  recipes:
  - EDHead
  - EDLegL
  - EDLegR
  - EDShell
  - ED209Endoskeleton
  - EDAiCoreElectronics
  - EDIFFElectronics
  - EDWeaponControlsElectronics
